### ISSUE TITLE
Plug/socket parenting in Maya

### ISSUE THREAD

**Issue by gabrieljreed** [DeRemerJD/Rig.Sys#33]
I've set up all the backend code for the multi plug/socket stuff to work, you just need to go in and actually do it. The documentation for it is all in the readme, I'm pretty pleased with the solution I came up with, but if we need to change it, we totally can.

Everything is ready for you in `rigsys/modules/utility/motionModuleParenting.py` in the `run()` function.

**Comment by DeRemerJD** [comment]
Plug socket code setup and updated, marking complete
